### ISSUE TITLE
None of the footprints conform to KLC

### ISSUE THREAD

**Issue by bobc** [KiCad/Connectors_IEC_DIN.pretty#3]
At time of writing, all footprints fail KLC according to check_kicad_mod.py

**Comment by jkriege2** [comment]
see my answer at https://github.com/KiCad/Mechanical_Sockets.pretty/issues/5 ... i.e. just go ahead and fix it ;-)

**Comment by SchrodingersGat** [comment]
If you still think this issue needs addressing please refer it to the new repository at https://github.com/kicad/kicad-footprints
