### ISSUE TITLE
Pin 24 should be named pin 24a

### ISSUE THREAD

**Issue by bobc** [KiCad/Connectors_IEC_DIN.pretty#4]
In some footprints, pin 24a is incorrectly labelled pin 24.

This affects 

Socket_DIN41612-CaseB1-Female_64Pin-2rows.kicad_mod
Socket_DIN41612-CaseC1-AC-Female-64Pin-2rows.kicad_mod
Socket_DIN41612-CaseC1-AC-Male-64Pin-2rows.kicad_mod
Socket_DIN41612-CaseC1-full-Female-96Pin-3rows.kicad_mod
Socket_DIN41612-CaseC1-full-Male-96Pin-3rows.kicad_mod

Fix: rename pad "24" to "24a".

**Comment by jkriege2** [comment]
see my answer at https://github.com/KiCad/Mechanical_Sockets.pretty/issues/5 ... i.e. just go ahead and fix it ;-)

**Comment by Ekran** [comment]
I did not find:

- Socket_DIN41612-CaseB1-Female_64Pin-2rows.kicad_mod
and https://github.com/KiCad/Connectors_IEC_DIN.pretty/pull/7 is the answer: "This is a complete replacement of the B family"
