### ISSUE TITLE
Replacing the footprints; way to go.

### ISSUE THREAD

**Issue by MRQ** [KiCad/Connectors_IEC_DIN.pretty#6]
The footprints in this library have multiple issues and repairing them seems to be as much work as replacing them. I am thinking about replacing them with generated versions, because I like the OpenSCAD workflow and then dimensions can be reliably tracked back to the datasheets.

So how should I be doing this? So far I am aiming for this workflow:
  1. clone https://github.com/pointhi/kicad-footprint-generator
  2. develop a generator in this repository in `scripts/Connectors_IEC_DIN.pretty` with no conventions how to be called and where to put the output.
  3. accomplish a pull request in the generator's github repository
  4. create a pull request with the output in this repository

**Comment by evanshultz** [comment]
@MRQ 
Excellent idea! Thanks for taking initiative to help fix up the old bits on the KiCad library.

You will have to figure out a lot for step 2. I would also swap 3 and 4. That way, you can get feedback on the resulting footprints and make sure they're good and approved before merging your script.

**Comment by MRQ** [comment]
The first script is finished and the footprint is the way I like it. Variants will follow, but I want to take this chance for a review.

* [This is the generating script](https://github.com/MRQ/kicad-footprint-generator/blob/master/scripts/Connectors_IEC_DIN/generate_din41612.py)
* [This is the output](https://github.com/MRQ/Connectors_IEC_DIN.pretty/blob/master/Conn_DIN41612_B-64-female.kicad_mod)
* [And this is a screenshot of the output](https://shells.aachen.ccc.de/~mrq/b-64-fem_rev1.png)

Some remarks:
* I intentionally changed the name. Reasons: The old names were to long. These connectors are no sockets. I want to make clear, that it's no improvement, but a replacement.
* The refdes on F.Fab is intentionally small to not clutter with the pins. I am open for criticism here.
* There is no pin 1, but a pin "A1" according to every document about DIN 41612 connectors. So I used this as an anchor.
* I left the orientation the way it is in all datasheets. Otherwise people might get confused when talking about rows (A, B, C) and columns (1..N).

**Comment by Shackmeister** [comment]
You should make sure to add the 3D model reference

**Comment by MRQ** [comment]
@Shackmeister: Please don't insist on the 3D model.
Creating 3D models for this connector family will be multiple times as much work as the footprints. I want to generate the footprints by script and there is no .wrl generator, so I first have to write one.

**Comment by Shackmeister** [comment]
Just the reference in the footprint :) not the model itself

**Comment by MRQ** [comment]
But what's the point in referencing a non existant file?

**Comment by Shackmeister** [comment]
The point is the model will be shown when made without any change in the footprint

**Comment by MRQ** [comment]
These connectors are typically offered with different pin populations. For example the C(/1) connectors are offered with:
* 96 pins, rows A, B, C, full population (3 * 32)
* 64 pins, rows A and C, full population (2 * 32)
* 48 pins, rows A, B, C, only even pins (3 * 16)
* 32 pins, row A and C, only even pins (2 * 16)

The modeling will be easier, if the designer only has to provide one plastic housing without pins and one pin model, that will assembled by the kicad_mod. At least my kicad version (git rev f3184ebad, master of 2017-10-02) supports multiple `model`s per footprint, but I have not seen a footprint in my library, that has multiple models.

@Shackmeister: Are multiple multiple models OK for a merge?

**Comment by MRQ** [comment]
[The first pull request](https://github.com/KiCad/Connectors_IEC_DIN.pretty/pull/7) got through and I will continue this way.
